# Generated by Django 4.2.11 on 2024-04-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Todo'), (2, 'In Progress'), (3, 'Completed'), (4, 'In Complete')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
